### ISSUE TITLE
NPE in onTripRetrieved()

### ISSUE THREAD

**Issue by grote** [grote/Transportr#204]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at android.content.ComponentName.<init>(ComponentName.java:128)
	at android.content.Intent.<init>(Intent.java:4653)
	at de.grobox.liberario.fragments.DirectionsFragment.onTripRetrieved(DirectionsFragment.java:297)
	at de.grobox.liberario.tasks.AsyncQueryTripsTask.onPostExecute(AsyncQueryTripsTask.java:152)
	at de.grobox.liberario.tasks.AsyncQueryTripsTask.onPostExecute(AsyncQueryTripsTask.java:42)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
```

**Comment by grote** [comment]
`getContext()` returns `null` while the screen is rotated after a search was started.
