### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by patkan** [grote/Transportr#251]
Thank you very much with your help so far in #71!
After the refactoring I am a bit stuck. I currently try to run the current `master`. However, I am unable to do this after the refactoring.
The build runs normally and succesfully, unfortunately on starting the application it crashes. I am running in Android 5.1.
Before building, I have checked out master, then have done `git submodule update` and run `./pre-build.sh`.
I am not quite sure where this error does come from. Please find the crashing stack-trace below.

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: de.grobox.liberario.debug, PID: 23813
                  java.lang.RuntimeException: Unable to resume activity {de.grobox.liberario.debug/de.grobox.liberario.activities.MainActivity}: java.lang.IllegalArgumentException: type ANY cannot have ID
                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2986)
                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
                      at android.app.ActivityThread.access$800(ActivityThread.java:151)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5254)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                   Caused by: java.lang.IllegalArgumentException: type ANY cannot have ID
                      at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
                      at de.schildbach.pte.dto.Location.<init>(Location.java:60)
                      at de.schildbach.pte.dto.Location.<init>(Location.java:0)
                      at de.grobox.liberario.data.RecentsDB.getLocation(RecentsDB.java:563)
                      at de.grobox.liberario.data.RecentsDB.getLocation(RecentsDB.java:551)
                      at de.grobox.liberario.data.RecentsDB.getFavLocationList(RecentsDB.java:64)
                      at de.grobox.liberario.data.RecentsDB.getFavLocationList(RecentsDB.java:76)
                      at de.grobox.liberario.adapters.LocationAdapter.getDefaultLocations(LocationAdapter.java:244)
                      at de.grobox.liberario.adapters.LocationAdapter.setDefaultLocations(LocationAdapter.java:219)
                      at de.grobox.liberario.ui.LocationView.reset(LocationView.java:372)
                      at de.grobox.liberario.ui.LocationView.resetIfEmpty(LocationView.java:378)
                      at de.grobox.liberario.fragments.DirectionsFragment.refreshAutocomplete(DirectionsFragment.java:476)
                      at de.grobox.liberario.fragments.DirectionsFragment.onResume(DirectionsFragment.java:232)
                      at android.support.v4.app.Fragment.performResume(Fragment.java:2126)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1151)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
                      at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2159)
                      at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
                      at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:507)
                      at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:496)
                      at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
                      at android.app.Activity.performResume(Activity.java:6090)
                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5254) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by grote** [comment]
Can you confirm that 754327e2cf5ceeddf0e717072eccb9b1cd7b2a21 is your latest commit that you have locally?

If so, the work from that commit might not have been complete, because that would mean that there is a `ANY` location in your database for some reason.

**Comment by patkan** [comment]
Yep, I have checked out commit `754327e`. I will try creating a new clone and building that one. Just to make sure that the problem it is not on my side.

**Comment by grote** [comment]
Great, then you found a bug! :)

Could you please give me the values that the `Location` object is constructed with right before the crash?

https://github.com/grote/Transportr/blob/master/src/de/grobox/liberario/data/RecentsDB.java#L557

This should provide some insight into what kind of location this is and where the problem lies.

**Comment by patkan** [comment]
The crash occurs after constructing the object `Location("ANY", "Transportr.GPS", 0, 0, null, null)`.
I am not 100% sure whether I used the debugger correctly, but I could reproduce this behavior. (Is there something like "postmortem-debugging" in Android Studio?)

**Comment by grote** [comment]
You would set a break-point before the crash happens and then run the debugger.

Or just add debug output [here](https://github.com/grote/Transportr/blob/master/src/de/grobox/liberario/data/RecentsDB.java#L557) and look at the one from right before the crash. The `"Transportr.GPS"` location should never enter the database, so I hope you debugged that wrong.

**Comment by patkan** [comment]
After further thinking about this, I might have accidentally created this entry while playing around with the intents. I have debugged again and I am now sure that I have debugged correctly.
So probably I have just "tainted" my database. This is probably not a usecase that the app should handle.
Do you want me to try anything else? Otherwise I will just try to reset my database.

**Comment by grote** [comment]
It would be nice if it would not be possible to "taint" the database in this way. It should probably refuse `ANY` locations from being added here: https://github.com/grote/Transportr/blob/master/src/de/grobox/liberario/data/RecentsDB.java#L107

Also I'd feel better if we knew for sure that this is really is what caused the issue.

**Comment by patkan** [comment]
After some tinkering I managed to reproduce the error. (I reset the database, created an intent that had such an `ANY`-location in the from address and then tried to search for i and  after the next start the error reappeared)
I am not very sure that the error has been introduced this way.

I will try to create a patch that blocks such entries from entering the database. (Will try your suggestion.)

**Comment by grote** [comment]
Thanks, so let's hope other people don't also have `ANY` locations in the database :P

**Comment by patkan** [comment]
Another option would be ignoring ANY-locations in the database while reading. In the best case it would throw an exception for the debug-build and ignore it in release.

**Comment by grote** [comment]
No this would just hide errors and potentially fill the database with garbage.
