### ISSUE TITLE
crash when entering arbitrary text in directions (refactoring incomplete)

### ISSUE THREAD

**Issue by patkan** [grote/Transportr#254]
There seems to be a regression in current `master`. When I enter arbitrary text as e.g. destination together with a valid from and hit Search the app will crash with the attached exception.
It seems to be reproducible with every network. My current commit is faa5c85b24f9c5d69b6977a53db762cc3352daa1.
The crash occurs on [line 497](https://github.com/grote/Transportr/blob/754327e2cf5ceeddf0e717072eccb9b1cd7b2a21/src/de/grobox/liberario/fragments/DirectionsFragment.java#L497-L497) in the DirectionsFragment.
I assume the problem is that this line has not been refactored. (It uses an ID for a location of type ANY)

```
11-04 13:18:33.979 10961-10961/de.grobox.liberario.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: de.grobox.liberario.debug, PID: 10961
                                                                           java.lang.IllegalArgumentException: type ANY cannot have ID
                                                                               at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
                                                                               at de.schildbach.pte.dto.Location.<init>(Location.java:60)
                                                                               at de.schildbach.pte.dto.Location.<init>(Location.java:0)
                                                                               at de.schildbach.pte.dto.Location.<init>(Location.java:0)
                                                                               at de.grobox.liberario.fragments.DirectionsFragment.checkLocation(DirectionsFragment.java:497)
                                                                               at de.grobox.liberario.fragments.DirectionsFragment.search(DirectionsFragment.java:365)
                                                                               at de.grobox.liberario.fragments.DirectionsFragment.access$500(DirectionsFragment.java:95)
                                                                               at de.grobox.liberario.fragments.DirectionsFragment$4.onClick(DirectionsFragment.java:175)
                                                                               at android.view.View.performClick(View.java:4781)
                                                                               at android.view.View$PerformClick.run(View.java:19874)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by grote** [comment]
Thanks looks indeed like I forgot to change that code path.
