### ISSUE TITLE
SQLiteFullException: database or disk is full (code 13)

### ISSUE THREAD

**Issue by eileenfan** [grote/Transportr#357]
//package name: de.grobox.liberario
//version: 1.1.7-debug
//target sdk version: android-18
 android.database.sqlite.SQLiteException: Failed to change locale for db '/storage/sdcard/osmdroid/tiles/cache.db' to 'en_US'.
 	at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:393)
 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
 	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:709)
 	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:702)
 	at org.osmdroid.tileprovider.modules.SqlTileWriter.<init>(SqlTileWriter.java:55)
 	at org.osmdroid.tileprovider.MapTileProviderBasic.<init>(MapTileProviderBasic.java:76)
 	at org.osmdroid.tileprovider.MapTileProviderBasic.<init>(MapTileProviderBasic.java:50)
 	at org.osmdroid.views.MapView.<init>(MapView.java:184)
 	at org.osmdroid.views.MapView.<init>(MapView.java:158)
 	at org.osmdroid.views.MapView.<init>(MapView.java:212)
 	at java.lang.reflect.Constructor.constructNative(Native Method)
 	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
 	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
 	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
 	at de.grobox.liberario.activities.MapActivity.onCreate(MapActivity.java:110)
 	at android.app.Activity.performCreate(Activity.java:5133)
 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)
 Caused by: android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
 	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
 	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
 	at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:371)

**Comment by grote** [comment]
This seems to originate in osmdroid and caused by a full disk. How do you expect to be handled otherwise?
v2 won't be using osmdroid, so this would take care of itself.

**Comment by grote** [comment]
v1 is not supported anymore.
