### ISSUE TITLE
IllegalStateException ListView

### ISSUE THREAD

**Issue by eileenfan** [grote/Transportr#358]
//package name: de.grobox.liberario
//version: 1.1.6-debug
//target sdk version: android-18
 java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. [in ListView(-1, class android.widget.ListPopupWindow$DropDownListView) with Adapter(class de.grobox.liberario.adapters.LocationAdapter)]
 	at android.widget.ListView.layoutChildren(ListView.java:1545)
 	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3442)
 	at android.view.View.dispatchTouchEvent(View.java:7384)
 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1940)
 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1954)
 	at android.widget.PopupWindow$PopupViewContainer.dispatchTouchEvent(PopupWindow.java:1592)
 	at android.view.View.dispatchPointerEvent(View.java:7564)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3883)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3778)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5419)
 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5399)
 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5370)
 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5493)
 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:182)
 	at android.os.MessageQueue.nativePollOnce(Native Method)
 	at android.os.MessageQueue.next(MessageQueue.java:132)
 	at android.os.Looper.loop(Looper.java:124)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by eileenfan** [comment]
Data should be updated in UI thread, and should immediately call notifyDataChanged() after the data was changed.

**Comment by grote** [comment]
Have you tried this with 1.1.8? The version you use is quite outdated.
