### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by eileenfan** [grote/Transportr#359]
//package name: de.grobox.liberario
//version: 1.1.6-debug
//target sdk version: android-18
 java.lang.RuntimeException: An error occured while executing doInBackground()
 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 	at java.lang.Thread.run(Thread.java:841)
 Caused by: java.lang.NullPointerException
 	at de.grobox.liberario.tasks.AsyncQueryNearbyStationsTask.doInBackground(AsyncQueryNearbyStationsTask.java:57)
 	at de.grobox.liberario.tasks.AsyncQueryNearbyStationsTask.doInBackground(AsyncQueryNearbyStationsTask.java:35)
 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)

**Comment by grote** [comment]
Have you tried this with 1.1.8? The version you use is quite outdated.
