### ISSUE TITLE
IllegalStateException in TripsRepository

### ISSUE THREAD

**Issue by grote** [grote/Transportr#430]
```
java.lang.IllegalStateException: 
 
  at de.grobox.transportr.trips.search.TripsRepository.searchMore (TripsRepository.kt:138)
 
  at de.grobox.transportr.trips.search.DirectionsViewModel.searchMore (DirectionsViewModel.java:237)
 
  at de.grobox.transportr.trips.search.TripsFragment.onRefresh (TripsFragment.java:145)
 
  at com.omadahealth.github.swipyrefreshlayout.library.SwipyRefreshLayout$1.onAnimationEnd (SwipyRefreshLayout.java:176)
 
  at com.omadahealth.github.swipyrefreshlayout.library.CircleImageView.onAnimationEnd (CircleImageView.java:108)
```

**Comment by grote** [comment]
Still exists when searching with `TLEM` provider:

```
java.lang.IllegalStateException: Can not query earlier
    at de.grobox.transportr.trips.search.TripsRepository.searchMore(TripsRepository.kt:142)
    at de.grobox.transportr.trips.search.DirectionsViewModel.searchMore(DirectionsViewModel.java:237)
    at de.grobox.transportr.trips.search.TripsFragment.onRefresh(TripsFragment.java:145)
    at com.omadahealth.github.swipyrefreshlayout.library.SwipyRefreshLayout$1.onAnimationEnd(SwipyRefreshLayout.java:176)
    at com.omadahealth.github.swipyrefreshlayout.library.CircleImageView.onAnimationEnd(CircleImageView.java:108)
```
