### ISSUE TITLE
App crashes when selecting transportation network on Replicant

### ISSUE THREAD

**Issue by 94b42c29dd** [grote/Transportr#496]
Since version 2.0 (including the latest 2.0.2) the app crashes when a transportation network is selected. Version 1.1.9 works perfectly. Reinstalling/removing data doesn't help.

OS: Replicant 6.0003

**Comment by grote** [comment]
Thanks for reporting!

Can you please provide a stacktrace of the crash via logcat? Thanks!

**Comment by 94b42c29dd** [comment]
08-05 17:28:13.399 D/libEGL  (19619): Emulator without GPU support detected. Fallback to software renderer.
08-05 17:28:13.469 D/libEGL  (19619): loaded /system/lib/egl/libGLES_android.so
08-05 17:28:13.534 E/AndroidRuntime(19619): FATAL EXCEPTION: GLThread 591
08-05 17:28:13.534 E/AndroidRuntime(19619): Process: de.grobox.liberario, PID: 19619
08-05 17:28:13.534 E/AndroidRuntime(19619): Theme: themes:{}
08-05 17:28:13.534 E/AndroidRuntime(19619): com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigException: eglChooseConfig() failed
08-05 17:28:13.534 E/AndroidRuntime(19619): 	at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig(EGLConfigChooser.java:65)
08-05 17:28:13.534 E/AndroidRuntime(19619): 	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
08-05 17:28:13.534 E/AndroidRuntime(19619): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
08-05 17:28:13.534 E/AndroidRuntime(19619): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
08-05 17:28:13.769 W/ActivityManager( 9464):   Force finishing activity de.grobox.liberario/de.grobox.transportr.map.MapActivity
08-05 17:28:13.779 W/InputMethodManagerService( 9464): Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@638f2b (uid=10084 pid=19619)
08-05 17:28:13.789 I/Choreographer(19619): Skipped 43 frames!  The application may be doing too much work on its main thread.
08-05 17:28:14.069 I/WindowManager( 9464): Screenshot max retries 4 of Token{262da04 ActivityRecord{7d5617 u0 de.grobox.liberario/de.grobox.transportr.map.MapActivity t114 f}} appWin=Window{6453f88 u0 SurfaceView} drawState=3
08-05 17:28:14.074 W/art     ( 9464): Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:13027 waiters=0 for 536ms
08-05 17:28:15.059 I/Choreographer(10198): Skipped 50 frames!  The application may be doing too much work on its main thread.
08-05 17:28:15.144 I/ActivityManager( 9464): Killing 18547:com.android.externalstorage/u0a9 (adj 15): empty #17

Never done that before. But i think i got the right part of the log. Please tell me if you need more.

**Comment by grote** [comment]
Thanks that looks like the right part and unfortunately is an issue with the map library. Seems that it thinks that the Replicant is an Emulator without GPU (OpenGL) support.

You could check if this is [known upstream](https://github.com/mapbox/mapbox-gl-native/issues/).

**Comment by 94b42c29dd** [comment]
I think this is the same issue:
https://github.com/DaylightingSociety/WhereAreTheEyes/issues/54

Referencing this issue, which says it's fixed in upstream:
https://github.com/mapbox/mapbox-gl-native/issues/7273

Is transportr using the latest version of mapbox-gl-native? If so it may not be fixed and the issue will need to be reopened.

**Comment by grote** [comment]
It is not clear in which version this should have been fixed. The comment was from Jan 4. Jan 10 they released v5.3.1. Transportr currently uses 5.5.0 which was released Mar 1, so it is unlikely to be fixed.

There's a [demo app](https://github.com/mapbox/mapbox-android-demo) that uses 6.3.0. Maybe you can check if that crashes.

**Comment by 94b42c29dd** [comment]
Unfortunately it still crashes with 6.3.0. So i guess they haven't fixed it yet.
```
08-07 17:26:12.394 D/libEGL  ( 4618): loaded /system/lib/egl/libGLES_android.so
08-07 17:26:12.404 I/ActivityManager( 9464): Displayed com.mapbox.mapboxandroiddemo/.examples.basics.SimpleMapViewActivity: +759ms
08-07 17:26:12.474 E/UncaughtException( 4618): 
08-07 17:26:12.474 E/UncaughtException( 4618): com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigException: eglChooseConfig() failed
08-07 17:26:12.474 E/UncaughtException( 4618): 	at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig(Unknown Source)
08-07 17:26:12.474 E/UncaughtException( 4618): 	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
08-07 17:26:12.474 E/UncaughtException( 4618): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
08-07 17:26:12.474 E/UncaughtException( 4618): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
08-07 17:26:12.479 E/AndroidRuntime( 4618): FATAL EXCEPTION: GLThread 934
08-07 17:26:12.479 E/AndroidRuntime( 4618): Process: com.mapbox.mapboxandroiddemo, PID: 4618
08-07 17:26:12.479 E/AndroidRuntime( 4618): Theme: themes:{}
08-07 17:26:12.479 E/AndroidRuntime( 4618): com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigException: eglChooseConfig() failed
08-07 17:26:12.479 E/AndroidRuntime( 4618): 	at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig(Unknown Source)
08-07 17:26:12.479 E/AndroidRuntime( 4618): 	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
08-07 17:26:12.479 E/AndroidRuntime( 4618): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
08-07 17:26:12.479 E/AndroidRuntime( 4618): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
08-07 17:26:12.489 W/ActivityManager( 9464):   Force finishing activity com.mapbox.mapboxandroiddemo/.examples.basics.SimpleMapViewActivity
08-07 17:26:12.489 W/ActivityManager( 9464):   Force finishing activity com.mapbox.mapboxandroiddemo/.MainActivity
```

**Comment by 94b42c29dd** [comment]
I have submitted the issue to mapbox-gl-native:
https://github.com/mapbox/mapbox-gl-native/issues/12567
