### ISSUE TITLE
[Crash] [VVT TNetwork] Departures 

### ISSUE THREAD

**Issue by Giant3** [grote/Transportr#623]
When touching on Departures (of a station) the up-coming site is blank and if you then swiping down the app crashes. This issue just appears to me if I use the VVT Transport Network.

**Comment by ialokim** [comment]
Same happens with Nicaragua provider.

The corresponding stacktrace is:
```
12-28 14:19:24.279 23510 23510 I DeparturesActivity: Count: 0 Get Item: -1
12-28 14:19:24.280 23510 23510 D AndroidRuntime: Shutting down VM
12-28 14:19:24.281 23510 23510 E AndroidRuntime: FATAL EXCEPTION: main
12-28 14:19:24.281 23510 23510 E AndroidRuntime: Process: de.grobox.liberario.debug, PID: 23510
12-28 14:19:24.281 23510 23510 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Asked to get item at -1 but size is 0
12-28 14:19:24.281 23510 23510 E AndroidRuntime: 	at androidx.recyclerview.widget.SortedList.get(SortedList.java:706)
12-28 14:19:24.281 23510 23510 E AndroidRuntime: 	at de.grobox.transportr.departures.DepartureAdapter.getItem(DepartureAdapter.java:96)
12-28 14:19:24.281 23510 23510 E AndroidRuntime: 	at de.grobox.transportr.departures.DeparturesActivity.loadMoreDepartures(DeparturesActivity.java:234)
12-28 14:19:24.281 23510 23510 E AndroidRuntime: 	at de.grobox.transportr.departures.DeparturesActivity.lambda$onCreate$0$DeparturesActivity(DeparturesActivity.java:127)
```
