### ISSUE TITLE
NoClassDefFoundError: LocalBroadcastManager

### ISSUE THREAD

**Issue by grote** [grote/Transportr#739]
These crashes happened during Google Play Pre-launch report testing on various API level for 6 devices in total.

```
FATAL EXCEPTION: main
Process: de.grobox.liberario, PID: 10800
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;
	at com.mapbox.services.android.telemetry.service.TelemetryService.onCreate(TelemetryService.java:41)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3542)
	at android.app.ActivityThread.-wrap4(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1786)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.localbroadcastmanager.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/de.grobox.liberario-D2vBpoatdDaUQL1N_DudlQ==/base.apk"],nativeLibraryDirectories=[/data/app/de.grobox.liberario-D2vBpoatdDaUQL1N_DudlQ==/lib/arm64, /data/app/de.grobox.liberario-D2vBpoatdDaUQL1N_DudlQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 10 more
```

```
FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: androidx.localbroadcastmanager.content.LocalBroadcastManager
	at com.mapbox.services.android.telemetry.service.TelemetryService.onCreate(TelemetryService.java:41)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2687)
	at android.app.ActivityThread.access$1700(ActivityThread.java:159)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1404)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5419)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ialokim** [comment]
I was able to reproduce this locally, will have to check what is going wrong here.

**Comment by ialokim** [comment]
Strangly enough, the crash only happens once after the first installation on my emulator - after selecting "Open app again" or if a previous version has been installed before, the app does start as expected.

That would mean existing users might perhaps even not experience the crash at all and for new users, it might only happen once directly after first installation (which is admittedly quite bad).

**Comment by ialokim** [comment]
The problem appears for the first time after https://github.com/grote/Transportr/commit/862182156fe19b5fc860dbd68388ff299f9b4791.

**Comment by ialokim** [comment]
See https://github.com/AltBeacon/android-beacon-library/issues/919 and https://stackoverflow.com/questions/60140990/getting-fatal-crash-using-startmonitoringbeaconsinregion/60141077#60141077.

A working solution at least for my testcase was adding `implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'` to `build.gradle`. Why the error only appeared after upgrading other (unrelated?) libraries and only on the first start of the app after a fresh install, remains a mystery to me.

This issue was blocking the release of the latest version `2.1.1` on Google and on F-Droid. @grote should we just publish a "fixup" version `2.1.2` without including further library upgrades (as per 91d42b51ca9bbb42de6f3d3852f36e462cc5449a) to make the changes available to the users (including many network fixes and (re-)additions, see https://github.com/grote/Transportr/releases/tag/2.1.1) or should we just include this fix on master for some future version?

**Comment by grote** [comment]
> should we just publish a "fixup" version 2.1.2 without including further library upgrades (as per 91d42b5) to make the changes available to the users (including many network fixes and (re-)additions, see https://github.com/grote/Transportr/releases/tag/2.1.1) or should we just include this fix on master for some future version?

I guess it depends on how fast we want to do another release. If we hadn't made that upgrade libs commit (which is now outdated anyway), doing a quick fixup release would be easier.

**Comment by ialokim** [comment]
Okay, I would then propose to revert 91d42b5 and do a fixup release in the next couple of days.
