### ISSUE TITLE
NullPointerException in TransportNetworks.getTransportNetwork

### ISSUE THREAD

**Issue by ByteHamster** [grote/Transportr#89]
Happening when clicking the app icon while the app was in background for a long time.
Unfortunately, this crash is not reliably reproducible. 

```
D/AndroidRuntime(31742): Shutting down VM
E/AndroidRuntime(31742): FATAL EXCEPTION: main
E/AndroidRuntime(31742): Process: de.grobox.liberario.debug, PID: 31742
E/AndroidRuntime(31742): java.lang.RuntimeException: Unable to start activity ComponentInfo{de.grobox.liberario.debug/de.grobox.liberario.activities.MainActivity}: java.lang.NullPointerException: 
        Attempt to invoke virtual method 'de.grobox.liberario.TransportNetwork de.grobox.liberario.TransportNetworks.getTransportNetwork(java.lang.String)' on a null object reference
E/AndroidRuntime(31742): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
// ...
E/AndroidRuntime(31742): Caused by: java.lang.NullPointerException: 
        Attempt to invoke virtual method 'de.grobox.liberario.TransportNetwork de.grobox.liberario.TransportNetworks.getTransportNetwork(java.lang.String)' on a null object reference
E/AndroidRuntime(31742): at de.grobox.liberario.Preferences.getTransportNetwork(Preferences.java:58)
E/AndroidRuntime(31742): at de.grobox.liberario.Preferences.getTransportNetwork(Preferences.java:51)
E/AndroidRuntime(31742): at de.grobox.liberario.fragments.PrefsFragment.onCreatePreferences(PrefsFragment.java:51)
E/AndroidRuntime(31742): at android.support.v7.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:215)
// ...
W/ActivityManager( 2479):   Force finishing activity 1
```

**Comment by grote** [comment]
I haven't seen this in a while. Please reopen if you observe this again.
