### ISSUE TITLE
query crashes when routing to "Freizeit- und Erholungszentrum"

### ISSUE THREAD

**Issue by woffs** [grote/Transportr#898]
**Describe the bug**
as reported in https://github.com/schildbach/public-transport-enabler/issues/550 the query crashes when routing to "Freizeit- und Erholungszentrum", which contains "- " (dash+space).

**To Reproduce**
- choose VBB as provider
- route from somewhere to "Freizeit- und Erholungszentrum"

**Expected behavior**
Routes as they appear when you choose destination POI "FEZ-Berlin", which works.

**Versions (please complete the following information):**
 - **Transportr Version:** 2.0.5
 - **Device:** Shiftphone 5me
 - **Android Version:** 8.1.0

**Comment by woffs** [comment]
sorry, I mistyped the version, I'm on 2.1.5

**Comment by woffs** [comment]
Same error when routing from a non-favourite start point. Same error when routing from "Freizeit- und Erholungszentrum" to anywhere. Maybe I should extract the sqlite DB (phone is rooted). :-)

**Comment by woffs** [comment]
- extracted transportr.db from phone
- only foreign_key is
```
CREATE TABLE `searches` (`uid` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `networkId` TEXT, `from_id` INTEGER NOT NULL, `via_id` INTEGER, `to_id` INTEGER NOT NULL, `count` INTEGER NOT NULL, `lastUsed` INTEGER, `favorite` INTEGER NOT NULL, FOREIGN KEY(`from_id`) REFERENCES `locations`(`uid`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`via_id`) REFERENCES `locations`(`uid`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`to_id`) REFERENCES `locations`(`uid`) ON UPDATE NO ACTION ON DELETE NO ACTION );
```
- db does not contain string "Freizeit"
- so I guess station name "Freizeit- und Erholungszentrum" can not be inserted into `locations` for some reason and then FOREIGN KEY fails
- or it is something completely different

**Comment by woffs** [comment]
logcat says a bit more:
```
12-18 22:23:58.021   918  3292 W System.err: android.database.sqlite.SQLiteConstraintException: 
FOREIGN KEY constraint failed (code 787)                            12-18 
22:23:58.024   918  3292 W System.err:    at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native 
Method)                        12-18 22:23:58.024   918  3292 W System.err:    
at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:783)                  
12-18 22:23:58.024   918  3292 W System.err:    at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)                        
12-18 22:23:58.024   918  3292 W System.err:    at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)                                   
12-18 22:23:58.024   918  3292 W System.err:    at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)            
12-18 22:23:58.024   918  3292 W System.err:    at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.java:114)                          
12-18 22:23:58.024   918  3292 W System.err:    at de.grobox.transportr.data.locations.LocationDao_Impl.addFavoriteLocation(LocationDao_Impl.java:195)              
12-18 22:23:58.024   918  3292 W System.err:    at de.grobox.transportr.data.locations.LocationRepository.addFavoriteLocation(LocationRepository.kt:88)             
12-18 22:23:58.024   918  3292 W System.err:    at de.grobox.transportr.trips.search.TripsRepository.queryTrips(TripsRepository.kt:121)                             
12-18 22:23:58.024   918  3292 W System.err:    at de.grobox.transportr.trips.search.TripsRepository.access$queryTrips(TripsRepository.kt:52)                       
12-18 22:23:58.024   918  3292 W System.err:    at de.grobox.transportr.trips.search.TripsRepository$search$1.invoke(TripsRepository.kt:104)                        
12-18 22:23:58.024   918  3292 W System.err:    at de.grobox.transportr.trips.search.TripsRepository$search$1.invoke(TripsRepository.kt:104)                        
12-18 22:23:58.024   918  3292 W System.err:    at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)                                                    
12-18 22:23:58.269   448   517 I BufferQueueProducer:
[de.grobox.liberario/de.grobox.transportr.trips.search.DirectionsActivity#0](this:0x7777662800,id:8235,api:1,p:918,c:448) 
queueBuffer: fps=34.56 dur=1012.72 max=266.12 min=10.81
```

**Comment by woffs** [comment]
Am 18.12.23 um 13:06 schrieb Frank Doepper:

> - so I guess station name "Freizeit- und Erholungszentrum" can not be inserted into `locations` for some reason and then FOREIGN KEY fails

same with "S+U Hauptbahnhof", I guess because of "+"
