### ISSUE TITLE
Die App stürzt bei einer Texteingabe im Suchfeld ab

### ISSUE THREAD

**Issue by rvs2000** [grote/Transportr#972]
Xiaomi 12
HyperOS 2.0, Android 14

App-Version 2.2.2 Beta

Wie es im Titel steht, stürzt jedes Mal bei einer Texteingabe ab. Ich vermute, die App versucht im Internet bzw. in einer Anbieter DB (zB Deutsche Bahn) etwas zu finden und fliegt dabei raus.

Das Gleiche passiert, wenn ich "Zuhause" o. "Arbeit" festzulegen versuche.

**Comment by rvs2000** [comment]
Die App stürzt komplett ab, ohne einer Fehlermeldung. Was ist ein
Stacktrace und wo finde ich es?

Altonss ***@***.***> schrieb am Di., 3. Dez. 2024, 09:12:

**Comment by rkunschke** [comment]
> Passiert das nur mir der DB?

Ich hab das selbe Problem. Passiert auch bei anderen Daten.

**Comment by rkunschke** [comment]
> Vielen Dank für den Bericht. Stürzt die App komplett ab? Könnten Sie einen Stacktrace teilen?

Ich weiß nicht ob das der richtige log ist. Ich hab das aus dem Android Debug Log:

'
      #152 TYPE_HIDE - STATUS_CANCEL - de.grobox.liberario:1186d5e1 (0ms):
        startTime=2024-12-03 10:13:04.506 ORIGIN_SERVER
        reason=HIDE_STATE_HIDDEN_FORWARD_NAV PHASE_SERVER_SHOULD_HIDE
        requestWindowName=not set
      #153 TYPE_SHOW - STATUS_SUCCESS - de.grobox.liberario:eba83713 (269ms):
        startTime=2024-12-03 10:13:09.548 ORIGIN_CLIENT
        reason=SHOW_SOFT_INPUT PHASE_CLIENT_ANIMATION_FINISHED_SHOW
        requestWindowName=9185faa de.grobox.liberario/de.grobox.transportr.map.MapActivity
      #154 TYPE_HIDE - STATUS_FAIL - de.grobox.liberario:328ecf62 (16ms):
        startTime=2024-12-03 10:13:10.996 ORIGIN_SERVER
        reason=HIDE_REMOVE_CLIENT PHASE_SERVER_APPLY_IME_VISIBILITY
        requestWindowName=9185faa de.grobox.liberario/de.grobox.transportr.map.MapActivity
      #155 TYPE_HIDE - STATUS_CANCEL - de.grobox.liberario:fd6362b1 (0ms):
        startTime=2024-12-03 10:13:14.703 ORIGIN_SERVER
        reason=HIDE_STATE_HIDDEN_FORWARD_NAV PHASE_SERVER_SHOULD_HIDE
        requestWindowName=not set
      #156 TYPE_HIDE - STATUS_CANCEL - de.grobox.liberario:58d87c72 (0ms):
        startTime=2024-12-03 10:13:16.036 ORIGIN_SERVER
        reason=HIDE_REMOVE_CLIENT PHASE_SERVER_SHOULD_HIDE
        requestWindowName=not set

'

**Comment by neunzehnachtneun** [comment]
I got the same error using Android 15.

https://pastebin.com/FbBTiNXs

**Comment by mv1005** [comment]
I had the same issue after upgrading from 2.2.1 to 2.2.2. 

Thanks for your fast response with the possible fix. I built from sources and can confirm it works, the issue is gone :tada:.

**Comment by mv1005** [comment]
After having a hard time figuring out how to generate a properly signed APK just for testing purposes, I finally managed to install the release build (see screenshot). And again, the app works!

![image_2024-12-05_13-17-56](https://github.com/user-attachments/assets/804a633b-329c-4608-9dc4-c80792361c3b)

**Comment by lintux** [comment]
Same Problem here with. 2.2.2 on android 13 Motorola g20 kernel 5.4.210-moto-gb08c11e61cb9
#1 Tue Aug 22 09:02:17 CDT 2023
Can it be that  öffi has a similar an related issue in the last version? Someone recognised that?

**Comment by mv1005** [comment]
@Altonss: May I somehow provide the APK-file I built so that others can try it out? Will that be helpful?

**Comment by Smojo** [comment]
Same here - can confirm that the issue still exist.

Device: Fairphone 5
OS: Android 14 (iodéOS 5.6-20241015-FP5)
App-Version: 2.2.2 - de.grobox.liberario

<details>
<summary>sccop - Transportr crash</summary>
`FATAL EXCEPTION: AsyncTask #1
Process: de.grobox.liberario, PID: 5391
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/slf4j/LoggerFactory;
	at de.schildbach.pte.AbstractHafasProvider.<clinit>(AbstractHafasProvider.java:55)
	at de.grobox.transportr.networks.TransportNetworksKt$networks$2.invoke(TransportNetworks.kt:53)
	at de.grobox.transportr.networks.TransportNetworksKt$networks$2.invoke(TransportNetworks.kt:39)
	at de.grobox.transportr.networks.TransportNetwork.getNetworkProviderReference(TransportNetwork.kt:51)
	at de.grobox.transportr.networks.TransportNetwork.access$getNetworkProviderReference(TransportNetwork.kt:32)
	at de.grobox.transportr.networks.TransportNetwork$networkProviderRef$2.invoke(TransportNetwork.kt:50)
	at de.grobox.transportr.networks.TransportNetwork$networkProviderRef$2.invoke(TransportNetwork.kt:50)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at de.grobox.transportr.networks.TransportNetwork.getNetworkProviderRef(TransportNetwork.kt:50)
	at de.grobox.transportr.networks.TransportNetwork.access$getNetworkProviderRef(TransportNetwork.kt:32)
	at de.grobox.transportr.networks.TransportNetwork$networkProvider$2.invoke(TransportNetwork.kt:49)
	at de.grobox.transportr.networks.TransportNetwork$networkProvider$2.invoke(TransportNetwork.kt:49)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at de.grobox.transportr.networks.TransportNetwork.getNetworkProvider(TransportNetwork.kt:49)
	at de.grobox.transportr.locations.SuggestLocationsTask.doInBackground(SuggestLocationsTask.java:48)
	at de.grobox.transportr.locations.SuggestLocationsTask.doInBackground(SuggestLocationsTask.java:31)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	... 22 more

`
</details>

**Comment by Smojo** [comment]
Can confirm that it works again here with 2.2.3. Thx

**Comment by lintux** [comment]
Same here

**Comment by secretmango** [comment]
Same here

```
type: crash
osVersion: google/bluejay/bluejay:15/AP4A.241205.013/2024121200:user/release-keys
flags: dev options enabled
package: de.grobox.liberario:126, targetSdk 34
process: de.grobox.liberario
processUptime: 3417 + 86 ms

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1117)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/slf4j/LoggerFactory;
	at de.schildbach.pte.AbstractHafasProvider.<clinit>(AbstractHafasProvider.java:55)
	at de.grobox.transportr.networks.TransportNetworksKt$networks$2.invoke(TransportNetworks.kt:53)
	at de.grobox.transportr.networks.TransportNetworksKt$networks$2.invoke(TransportNetworks.kt:39)
	at de.grobox.transportr.networks.TransportNetwork.getNetworkProviderReference(TransportNetwork.kt:51)
	at de.grobox.transportr.networks.TransportNetwork.access$getNetworkProviderReference(TransportNetwork.kt:32)
	at de.grobox.transportr.networks.TransportNetwork$networkProviderRef$2.invoke(TransportNetwork.kt:50)
	at de.grobox.transportr.networks.TransportNetwork$networkProviderRef$2.invoke(TransportNetwork.kt:50)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at de.grobox.transportr.networks.TransportNetwork.getNetworkProviderRef(TransportNetwork.kt:50)
	at de.grobox.transportr.networks.TransportNetwork.access$getNetworkProviderRef(TransportNetwork.kt:32)
	at de.grobox.transportr.networks.TransportNetwork$networkProvider$2.invoke(TransportNetwork.kt:49)
	at de.grobox.transportr.networks.TransportNetwork$networkProvider$2.invoke(TransportNetwork.kt:49)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at de.grobox.transportr.networks.TransportNetwork.getNetworkProvider(TransportNetwork.kt:49)
	at de.grobox.transportr.locations.SuggestLocationsTask.doInBackground(SuggestLocationsTask.java:48)
	at de.grobox.transportr.locations.SuggestLocationsTask.doInBackground(SuggestLocationsTask.java:31)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	... 22 more
```
